"""adds audit tables

Revision ID: bda0595e7d2
Revises: 41837dc547ce3
Create Date: 2016-04-25 09:54:45.869664

"""

# revision identifiers, used by Alembic.
revision = 'bda0595e7d2'
down_revision = '41837dc547ce3'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quark_audit_datacenters',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('name', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_engine='InnoDB'
    )
    op.create_table('quark_audit_network_types',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('type', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type'),
    mysql_engine='InnoDB'
    )
    op.create_table('quark_audit_operations',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('operation', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation'),
    mysql_engine='InnoDB'
    )
    op.create_table('quark_audit_resources',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('resource', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource'),
    mysql_engine='InnoDB'
    )
    op.create_table('quark_audit_versions',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('version', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version'),
    mysql_engine='InnoDB'
    )
    op.create_table('quark_audit_networks',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False, autoincrement=True),
    sa.Column('network_id', sa.String(length=36), nullable=True),
    sa.Column('network_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['network_type_id'], ['quark_audit_network_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('quark_audits',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False, autoincrement=True),
    sa.Column('resource_desc', sa.String(length=64), nullable=True),
    sa.Column('resource_key', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=16), nullable=False),
    sa.Column('instance_uuid', sa.String(length=36), nullable=True),
    sa.Column('datacenter_id', sa.Integer(), nullable=True),
    sa.Column('network_id', sa.BigInteger(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['datacenter_id'], ['quark_audit_datacenters.id'], ),
    sa.ForeignKeyConstraint(['network_id'], ['quark_audit_networks.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['quark_audit_operations.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['quark_audit_resources.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['quark_audit_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('quark_audit_details',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False, autoincrement=True),
    sa.Column('contents', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('audit_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['quark_audits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quark_audit_details')
    op.drop_table('quark_audits')
    op.drop_table('quark_audit_networks')
    op.drop_table('quark_audit_versions')
    op.drop_table('quark_audit_resources')
    op.drop_table('quark_audit_operations')
    op.drop_table('quark_audit_network_types')
    op.drop_table('quark_audit_datacenters')
    ### end Alembic commands ###
